name: 'send greating action'
description: 'who to great'

inputs:
   who-to-great:
     description: 'who to great'
     required: true
     default: 'kenny ngoe'
outputs:
    random_number_out:
       description: random number
       value: ${{ steps.random_number_generator.outputs.random_number_out}}   


runs:
  using: 'composite'
  steps:
     - name: send great
       run: echo "hello $greatings"
       shell: bash 
       env:
          greatings: ${{inputs.who-to-great}}
          

     - name: random number
       shell: bash
       id: random_number_generator
       run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

