name: testing to access the environmental variable 

on:
    workflow_dispatch:
jobs:
    accessing_var:
        runs-on: ubuntu-latest 
        environment: production
        env:
            SECREATE_KEY: ${{secrets.SECREATE_KEY_HERE}}
        steps:
            - name: environmental
              run: |
                   echo "$SECREATE_KEY"       