name: action up on pull request

on:
    # push:
        # branches:
        #     - features/home
    workflow_dispatch:

    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - "data_html/*.html"
            - "text/*.txt"
jobs:
    pull_request_workflow:
        runs-on: ubuntu-24.04
        steps:
            - name: pull request actions 
              run: |
               echo "===$GITHUB_EVENT_NAME=="
               cat "$GITHUB_EVENT_PATH"
              


